{% set name = "ale" %}
{% set version = "0.8.5" %}
package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  path: ../../ale
  patches:
    - patches/parse.patch

build:
  number: 3
  skip: true  # [py2k]

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake >=3.15
    - eigen
    - cspice
  host:
    - python
    - nlohmann_json
    - pip
    - setuptools
  run:
    - networkx
    - nlohmann_json
    - numpy
    - pvl >=1.0
    - python=3.6.7
    - python-dateutil
    - pytz
    - scipy >=1.2.0,<1.6.0
    - spiceypy ==2.3.2
    - pyyaml
    - setuptools

test:
  requires:
    - setuptools
  imports:
    - ale
  commands:
    - test -e $PREFIX/lib/libale${SHLIB_EXT}  # [unix]
    - if not exist %LIBRARY_BIN%\ale.dll exit 1  # [win]
    - if not exist %LIBRARY_LIB%\ale.lib exit 1  # [win]

about:
  home: https://github.com/USGS-Astrogeology/ale
  license: Unlicense
  license_file: LICENSE
  summary: Abstraction Library for Ephemerides (ALE) for extracting and processing planetary sensor ephemeris data.

extra:
  recipe-maintainers:
    - jlaura
    - jessemapel
